### ISSUE TITLE
Odd thing happened to my iphone after I tried this

### ISSUE THREAD

**Issue by carringtny** [toshmatik/VMWare-iMessage#3]
I am trying to figure out if using this method caused an issue on my iphone. Literally, 5 minutes after going through these steps and getting imessages working in the Mac virtual environment and connected to my account, my service dropped on my iphone. The only way I could get it back was calling Sprint, and on their end they did something and I had to dial some number starting with ##.  After this happening over the next few days, it got to the point where the service couldn't' be restored. I then went in to the sprint store and they gave me a new SIM to try. There was no change. Still no service after 2 days. Next I was going to head to their support center, but then finally last night a message popped on my iphone saying my phone has been activated. So far it is still working. 

The only thing I can correlate to the issue is using the described method here to get imessages working. Soon after all this happened, I took off the imessages from my account. I want to try it again, but am wondering if all my issues were some detection system on Apple/Sprint's end that things the phone is stolen due to setting up the hacked version of imessages on the Mac VM. Either setting up imessages in this way is related to the issues, or I just had a bad luck happenstance where the issue happened minutes after I completed getting imessages configured on the Mac VM.

**Comment by toshmatik** [comment]
Well, the general method of making iMessage work, the way it is described here, is used by many thousands of hackintoshers around the world. I have never heard about someone loosing cell/data service on their iOS device because of that. I don't see a correlation here.

But if you're curious try [/r/hackintosh](https://www.reddit.com/r/hackintosh/), they might be able to tell you, if they had similar problems when trying to activate iMessage. Unfortunaly i can't help you further. And honestly, i don't use a Hackintosh anymore, so i might be a bit (or a lot) out of the loop.

**Comment by carringtny** [comment]
Ok, thanks. It was just so odd. Your solution is the only one that I could find anywhere that worked and it worked so awesome. I am tempted to sign into my account again in imessages and see if it happens again, but maybe I'll try the subreddit first and see if anyone has had similar issues. Thanks for putting this together and responding.
